version: '3.5'
name: junior_internet_2023

services:
  mysql:
    image: mysql:8.0.28-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '1111'
    ports:
      - 3333:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql

volumes:
  mysql: null
